### ISSUE TITLE
aws_rds_instance undefined method `engine`

### ISSUE THREAD

**Issue by evanpratama** [inspec/inspec-aws#218]
Just starting to use Inspec, and followed the examples for aws_rds_instance, but it keeps showing 'undefined method'

inspect.yml:
```
name: rds
title: InSpec Profile
maintainer: The Authors
copyright: The Authors
copyright_email: you@example.com
license: Apache-2.0
summary: An InSpec Compliance Profile
version: 0.1.0
inspec_version: '>= 4.6.9'
depends:
  - name: inspec-aws
    url: https://github.com/inspec/inspec-aws/archive/v1.14.0.tar.gz
supports:
  - platform: aws
```

Control:
```
describe aws_rds_instance(db_instance_identifier: 'myrds') do
  it { should exist }
  its('engine') { should eq 'mysql' }
end
```

Output:
```
RDS Instance myrds
     ✔  is expected to exist
     ×  engine 
     undefined method `engine' for #<#<Class:0x0000000005ece190>:0x0000000005ecda38>
```

I'm not sure what I did wrong in the configs.
