### ISSUE TITLE
aws_ec2_instances filtering by tags does not work

### ISSUE THREAD

**Issue by jeremymcgee73** [inspec/inspec-aws#255]
# Describe the problem

I am trying to run the examples from the documentation to filter ec2 instances by tags. I am running version 4.22.22 and I am getting an error.

This works:
```
    aws_ec2_instances.instance_ids.each do |instance_id|
      describe aws_ec2_instance(instance_id) do
        it              { should_not have_roles }
        its('key_name') { should cmp 'admin-ssh-key' }
        its('image_id') { should eq 'ami-27a58d5c' }
      end
    end
```

This does not:
```
    aws_ec2_instances.where(tags: {"Environment" => "Dev"}).instance_ids.each do |id|
      describe aws_ec2_instance(id) do
        it { should be_stopped }
      end
    end    
```

Error:
```
    Failed to load source for test.rb: ':tags' is not a recognized criterion - expected one of :instance_id'
```

**Comment by omerdemirok** [comment]
Hi @jeremymcgee73,

Can you try the following?
```
    aws_ec2_instances.where { tags["Environment"] == "Dev" }.instance_ids.each do |id|
      describe aws_ec2_instance(id) do
        it { should be_stopped }
      end
    end
```

**Comment by jeremymcgee73** [comment]
I'm still getting an error.

    Failed to load source for test.rb: undefined local variable or method `tags' for #<struct instance_id="i-INSTANCEID">

**Comment by omerdemirok** [comment]
Can you share the inspec.yml of the profile?

**Comment by jeremymcgee73** [comment]
I am not using one. I am running the test with the following command.

    inspec exec test.rb -t aws://

**Comment by omerdemirok** [comment]
Can you follow the steps explained here for using the AWS resource pack resources?
https://github.com/inspec/inspec-aws#use-the-resources

Ensure to replace `x` with the latest version of the resource pack in inspec.yml.
```depends:
  - name: inspec-aws
    url: https://github.com/inspec/inspec-aws/archive/v1.29.1.tar.gz
```

**Comment by jeremymcgee73** [comment]
I am still getting the same error. Thanks for your help!

```
name: jeremy
title: InSpec Profile
maintainer: The Authors
copyright: The Authors
copyright_email: you@example.com
license: Apache-2.0
summary: An InSpec Compliance Profile
inspec_version: '>= 4.6.9'
depends:
  - name: inspec-aws
    url: https://github.com/inspec/inspec-aws/archive/v1.29.1.tar.gz
version: 0.1.0
supports:
  platform: aws
```

    Failed to load source for controls/example.rb: undefined local variable or method `tags' for #<struct instance_id="INSTANCEIDVALUE">
