### ISSUE TITLE
undefined method `aws_internet_gateway'

### ISSUE THREAD

**Issue by gavinmoorcroft** [inspec/inspec-aws#264]
We are getting a undefined method error when using the aws_internet_gateway resource.

I've reduced the control down to a very simple: 

```
title "Internet Gateway Coverage"
control "Internet Gateway Test" do
  describe aws_internet_gateway(id: 'igw-0ef43252e8149f945') do
    it { should exist }
  end
end
```

and when executed we get:

```
  ×  Internet Gateway Test: ./controls/internet_gateway.rb:3
     ×  Control Source Code Error ./controls/internet_gateway.rb:3
     undefined method `aws_internet_gateway' for #<Inspec::Rule:0x000055b167eb02d0>
     Did you mean?  aws_transit_gateway
```

Our inspec.yml contains:

```
name: inspec_internet_gateway_resource
title: InSpec INTERNET GATEWAY RESOURCE
license: Apache-2.0
summary: An InSpec Compliance Profile for testing INTERNET GATEWAY RESOURCE
version: 0.0.1
inspec_version: '>=4.6.9'
depends:
  - name: inspec-aws
    url: https://github.com/inspec/inspec-aws/archive/v1.9.0.tar.gz
supports:
  - platform: aws
```

Thanks for any guidance you can offer on this.

**Comment by omerdemirok** [comment]
@gavinmoorcroft 

Can you try?
- Delete `inspec.lock` file
- Update the version of the resource pack in `inspec.yml`
```
depends:
  - name: inspec-aws
    url: https://github.com/inspec/inspec-aws/archive/v1.29.9.tar.gz
supports:
  - platform: aws
```
