### ISSUE TITLE
Dependency inspec-aws would cause a dependency cycle (inspec-aws -> inspec-aws)

### ISSUE THREAD

**Issue by tomasz-bres** [inspec/inspec-aws#815]
# Describe the problem
I'd like to use local inspec-aws resources.
I've cloned the repo to local folder and have updated the inspec.yml file as follows

```
name: el-aws
title: InSpec Profile
maintainer: The Authors
copyright: The Authors
copyright_email: you@example.com
license: Apache-2.0
summary: An InSpec Compliance Profile
version: 0.1.0
inspec_version: '>= 4.6.9'
depends:
  - name: inspec-aws
    # url: https://github.com/inspec/inspec-aws/archive/v1.74.87.tar.gz
    path: ../el-aws
  - name: aws-sdk
supports:
  - platform: aws
```
The file structure of el-profile:
```
$ tree -L 2  
.
└── el-aws
    ├── controls
    ├── files
    ├── inspec-aws
    ├── inspec.yml
    └── README.md
```

Executing inspec ends up with 
```
$ AWS_PROFILE=sbx inspec exec . -t aws:// --show-progress
Dependency inspec-aws would cause a dependency cycle (inspec-aws -> inspec-aws)
```

What am I doing wrong?
